In [59]:
import pandas as pd
import numpy as np

In [60]:
new_df = pd.read_csv(r'D:\DA_data\Data_analytics\power Bi project\Upi Transaction\Cleaning_prectice\messy_employee_data.csv')

### Data Cleaning

In [61]:
new_df.head()

,row_num,id,full_name,age,gender,country,salary,join_date,department,email,performance_rating,years_experience,is_active
0,1,41,Fatima Ivanov,62,Female,U.K.,"$102,304",2022-10-08 00:00:00,hr,NaN,2.1,4.0,yes
1,2,54,Fatima Kim,58,NaN,U.K.,-1000,NaN,sales,NaN,-2,-3.0,yes
2,3,35,Emma Silva,twenty five,female,USA,"$50,042","May 14, 2019",hr,emma.silva777@EXAMPLE.com,-2,28.0,No
3,4,110,Sam Diaz,-5,Female,US,84k,"May 14, 2019",finance,NaN,five,-3.0,0
4,5,160,mike rossi,41,female,Germany,84k,"May 14, 2019",NaN,mike.rossi795@EXAMPLE.com,3.2,9.0,TRUE

In [62]:
new_df.shape

(178, 13)

In [63]:
new_df.columns

Index(['row_num', 'id', 'full_name', 'age', 'gender', 'country', 'salary',
       'join_date', 'department', 'email', 'performance_rating',
       'years_experience', 'is_active'],
      dtype='object')

In [64]:
new_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 178 entries, 0 to 177
Data columns (total 13 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   row_num             178 non-null    int64
 1   id                  178 non-null    int64
 2   full_name           178 non-null    object
 3   age                 156 non-null    object
 4   gender              149 non-null    object
 5   country             170 non-null    object
 6   salary              117 non-null    object
 7   join_date           147 non-null    object
 8   department          158 non-null    object
 9   email               145 non-null    object
 10  performance_rating  145 non-null    object
 11  years_experience    98 non-null     float64
 12  is_active           160 non-null    object
dtypes: float64(1), int64(2), object(10)
memory usage: 18.2+ KB

In [65]:
# working with Text Data

# we can also use like
'''
df['full_name] = df['full_name'].str.strip().str.title()
df['full_name'] = df['full_name'].str.strip().str.capitalize()

'''
new_df['full_name'] = new_df['full_name'].str.strip()
new_name = []
for name in new_df['full_name']:
    if isinstance(name, str) and len(name) > 0:
        name = name.lower()
        formatted_name = name[0].upper() + name[1:]
        new_name.append(formatted_name)
    else:
        new_name.append(name)
new_df['full_name'] = new_name

new_df['full_name'] = new_df['full_name'].str.rstrip('.')
print(new_df['full_name'])

0      Fatima ivanov
1         Fatima kim
2         Emma silva
3           Sam diaz
4         Mike rossi
           ...
173         Sam chen
174       Sara smith
175       Anna kelly
176        Anna chen
177       Wei ivanov
Name: full_name, Length: 178, dtype: object

In [66]:
new_df['gender'] = new_df['gender'].str.strip().str.title()
new_df[new_df['gender'].isnull()]
new_df['gender'] = new_df['gender'].fillna('Unknown')
new_df['gender']
new_active = []
for i in new_df['gender']:
    if i ==  'M':
        i = 'Male'
        new_active.append(i)
    elif i == 'F':
        i = 'Female'
        new_active.append(i)
    else:
        new_active.append(i)
new_df['gender'] = new_active
new_df['gender'].unique()

array(['Female', 'Unknown', 'Male'], dtype=object)

In [67]:
new_df['country'] = new_df['country'].str.strip('.').str.lower()

country_map = {
    'us': 'usa', 'united states': 'usa', 'usa': 'usa',
    'uk': 'united kingdom', 'u.k': 'united kingdom', 'u.k.': 'united kingdom',
    'united kingdom': 'united kingdom',
    'in': 'india', 'india': 'india',
    'fr': 'france', 'france': 'france',
}
new_df['country'] = new_df['country'].map(country_map).fillna(new_df['country'])
new_df['country']  = new_df['country'].fillna('Not Provided')
new_df['country'] = new_df['country'].str.title()
new_df['country'].unique()

array(['United Kingdom', 'Usa', 'Germany', 'Canada', 'India', 'France',
       'Not Provided'], dtype=object)

In [68]:
new_df['department'] = new_df['department'].str.strip('.').str.title()
new_df['department'] = new_df['department'].fillna('Not Provided')
new_df['department'] = new_df['department'].str.replace('I.T','Information Technology', regex=True)
new_df['department'] = new_df['department'].replace({'Hr':'Human Resource', 'It':'Information Technology'}, regex=False)
new_df['department'].unique()

array(['Human Resource', 'Sales', 'Finance', 'Not Provided', 'Marketing',
       'Information Technology', 'Operations'], dtype=object)

Working with numerical columns

In [30]:
new_df.describe()

          row_num          id  years_experience
count  178.000000  178.000000         98.000000
mean    89.500000   81.494382          6.428571
std     51.528309   48.010856         13.184652
min      1.000000    1.000000         -3.000000
25%     45.250000   40.250000         -3.000000
50%     89.500000   79.500000         -3.000000
75%    133.750000  122.750000         14.000000
max    178.000000  165.000000         40.000000

In [71]:
new_df.tail(10)
new_df.sample(15)
new_df.tail(10)

,id,full_name,age,gender,country,salary,join_date,department,email,performance_rating,years_experience,is_active
168,157,Emma brown,64,Female,Canada,33k,NaN,Sales,emma.brown509@example.com,NaN,-3.0,yes
169,158,Carlos garcia,61,Female,Usa,30772,14-05-2019,Information Technology,carlos.garcia943@EXAMPLE.com,1.7,NaN,no
170,159,David ahmed,-5,Male,France,40650,2019/05/14,Not Provided,david.ahmed529@example.com,-2,-3.0,N
171,159,David ahmed,-5,Male,France,40650,2019/05/14,Not Provided,david.ahmed529@example.com,-2,-3.0,N
172,160,Mike rossi,41,Female,Germany,84k,"May 14, 2019",Not Provided,mike.rossi795@EXAMPLE.com,3.2,9.0,TRUE
173,161,John ahmed,twenty five,Male,Germany,-1000,2021-06-13 00:00:00,Marketing,john.ahmed543@EXAMPLE.com,4.8,17.0,Yes
174,162,Fatima nguyen,200,Male,India,NaN,not available,Finance,fatima.nguyen64@example.com,11,-3.0,TRUE
175,163,David johnson,35,Female,India,101638,"May 14, 2019",Human Resource,david.johnson322@example.com,2.4,-3.0,FALSE
176,164,Carlos garcia,-5,Unknown,Usa,53183,14-05-2019,Information Technology,carlos.garcia526@example.com,2.0,NaN,FALSE
177,165,Zoe rossi,24,Male,India,"$33,083","May 14, 2019",Information Technology,NaN,NaN,16.0,Yes

In [70]:
new_df['id'].head(20)
new_df = new_df.sort_values(by='id', ascending=True)
new_df = new_df.reset_index(drop=True)

## fixing the row number 
new_df.drop('row_num', axis = 1, inplace = True)

In [73]:
new_df['age'] = pd.to_numeric(new_df['age'], errors='coerce')
new_df['age'] = new_df['age'].abs()
new_df.loc[new_df['age'] >= 100 , 'age'] = np.nan
missing_count =new_df['age'].isnull().sum()
random_values = np.random.randint(20, 60, size = missing_count)
new_df.loc[new_df['age'].isnull(), 'age'] = random_values

new_df['age'] = new_df['age'].astype(int)

In [76]:
#new_df['salary'] = new_df['salary'].str.replace('k', '000', regex=True)
#new_df['salary'] = new_df['salary'].str.replace(r'[^a-zA-Z0-9 ]', '', regex=True)
missing_salary = new_df['salary'].isnull().sum()
random_value = np.random.randint(5000, 35000, size = missing_salary)
new_df.loc[new_df['salary'].isnull(), 'salary'] = random_value
new_df['salary'] = pd.to_numeric(new_df['salary'], errors='coerce')
new_df['salary'].value_counts()

new_df['salary'] = new_df['salary'].astype(float)

In [77]:
new_df['years_experience'] = new_df['years_experience'].abs()
# wrong data fixing
new_df.loc[new_df['years_experience'] > 6, 'years_experience'] = np.nan

missing_years= new_df['years_experience'].isnull().sum()
random_value = np.random.randint(1, 5, size = missing_years)
new_df.loc[new_df['years_experience'].isnull(), 'years_experience'] = random_value

"""
count_v = len(new_df[new_df['years_experience'] == 3.0])
random_value = np.random.randint(1, 5, size = count_v)
new_df.loc[(new_df['years_experience'] == 3), 'years_experience'] = random_value 

"""
new_df['years_experience'].value_counts()

years_experience
3.0    81
1.0    35
2.0    32
4.0    26
0.0     2
6.0     1
5.0     1
Name: count, dtype: int64

In [78]:
new_df['is_active'] = new_df['is_active'].str.title()
# new_df['is_active'] = np.where(new_df['is_active'] =='TRUE' ,'Yes','No')
new_active = []
for i in new_df['is_active']:
    if i in  ['True','1','Y']:
        i = 'Yes'
        new_active.append(i)
    elif i in ['False', 'N', '0']:
        i = 'No'
        new_active.append(i)
    else:
        new_active.append(i)

new_df['is_active'] = new_active

new_df['is_active'] =  new_df['is_active'].fillna('Unknown')

In [79]:
new_df.loc[new_df['performance_rating']== 'five', 'performance_rating'] = 5
new_df['performance_rating'] = pd.to_numeric(new_df['performance_rating'], errors='coerce')
new_df['performance_rating'] = new_df['performance_rating'].abs()
new_df['performance_rating'].values
new_df.loc[new_df['performance_rating'] > 6, 'performance_rating'] = np.nan
rating_mean = new_df['performance_rating'].median()

new_df['performance_rating'] = new_df['performance_rating'].fillna(rating_mean).astype(int)

In [ ]:
new_df['join_date'].apply(type).value_counts()
new_df['join_date'] = new_df['join_date'].replace(['not available', 'Not Provided', 'N/A'], np.nan)
new_df['join_date'].unique()

array(['2019/05/14', '2019-02-23 00:00:00', '14-05-2019', nan,
       '2020-09-07 00:00:00', 'May 14, 2019', '2020-07-26 00:00:00',
       '2020-10-20 00:00:00', '2018-02-09 00:00:00',
       '2020-12-23 00:00:00', '2024-02-23 00:00:00',
       '2021-10-04 00:00:00', '2022-10-08 00:00:00',
       '2023-02-06 00:00:00', '2019-09-25 00:00:00',
       '2024-09-11 00:00:00', '2024-09-14 00:00:00',
       '2022-11-28 00:00:00', '2020-10-19 00:00:00',
       '2022-12-29 00:00:00', '2019-08-01 00:00:00',
       '2023-04-19 00:00:00', '2020-02-29 00:00:00',
       '2018-07-18 00:00:00', '2018-10-29 00:00:00',
       '2024-02-05 00:00:00', '2018-12-18 00:00:00',
       '2022-06-09 00:00:00', '2019-08-09 00:00:00',
       '2022-04-30 00:00:00', '2019-12-21 00:00:00',
       '2021-06-13 00:00:00'], dtype=object)

In [ ]:
formats = [
    '%Y-%m-%d %H:%M:%S',
    '%Y-%m-%d',           
    '%Y/%m/%d',        
    '%d-%m-%Y',          
    '%B %d, %Y',      
]

parsed = pd.Series(pd.NaT, index=new_df.index)

for fmt in formats:
    still_unparsed = parsed.isna() & new_df['join_date'].notna()
    parsed.loc[still_unparsed] = pd.to_datetime(
        new_df.loc[still_unparsed, 'join_date'], format=fmt, errors='coerce'
    )

new_df['join_date'] = parsed

print(new_df['join_date'].dtype)                 
print(new_df['join_date'].isnull().sum())      
print(new_df[new_df['join_date'].isnull()])

datetime64[ns]
58
      id      full_name  age   gender         country    salary join_date  \
5      6  Ravi williams   44     Male             Usa   45033.0       NaT
6      7     Sara rossi   59   Female          Canada    1000.0       NaT
15    14      Anna chen   58     Male         Germany   22712.0       NaT
20    19       Ali khan    5   Female  United Kingdom   10927.0       NaT
23    22       Sam chen   52     Male  United Kingdom    1000.0       NaT
30    27      Nina wang    5  Unknown    Not Provided    5164.0       NaT
31    28     Ravi brown   49   Female          Canada   23203.0       NaT
32    29      Zoe rossi   49   Female          Canada   74000.0       NaT
35    32      Maria kim   28  Unknown             Usa   29361.0       NaT
39    36     Anna ahmed    5  Unknown          France   92000.0       NaT
40    36     Anna ahmed    5  Unknown          France   92000.0       NaT
43    39      Mike diaz   38   Female             Usa   11191.0       NaT
52    46     John rossi   23     Male           India    1000.0       NaT
53    47        Wei kim   65   Female          Canada   69548.0       NaT
58    51     Anna smith    5   Female          France    9302.0       NaT
60    53      Wei kumar   43  Unknown          France  114000.0       NaT
61    54     Fatima kim   58  Unknown  United Kingdom    1000.0       NaT
63    56      Ali ahmed   53   Female             Usa   13591.0       NaT
68    61    Priya silva   47  Unknown           India   82000.0       NaT
69    62      John khan   56     Male    Not Provided  118375.0       NaT
71    64   Lisa johnson   33     Male             Usa    9120.0       NaT
72    65  Sara martinez   53     Male         Germany  103696.0       NaT
74    67      Ali smith   51   Female          Canada   45000.0       NaT
75    67      Ali smith   51   Female          Canada   45000.0       NaT
90    81       Ravi lee    5     Male         Germany   29000.0       NaT
91    82      Ali rossi   51   Female  United Kingdom   40970.0       NaT
93    84      Nina khan   31     Male          France    1000.0       NaT
94    85    Priya brown   63   Female  United Kingdom   30000.0       NaT
96    87   Anna johnson   57   Female         Germany   28542.0       NaT
100   91    Priya patel   50   Female           India   28000.0       NaT
102   93      Tom brown    5   Female          France   35000.0       NaT
103   94      Sam brown   20  Unknown         Germany   98874.0       NaT
107   98    John garcia   21   Female          France   72964.0       NaT
108   99   Maria garcia    5   Female          France   29376.0       NaT
109  100   Maria nguyen    5     Male          France  100000.0       NaT
110  101  Sara martinez   48     Male    Not Provided   27000.0       NaT
120  111   Fatima ahmed   25  Unknown          France   34059.0       NaT
121  112       Emma lee   21  Unknown  United Kingdom   95341.0       NaT
124  114      Nina khan   29   Female          France    5071.0       NaT
126  116     John ahmed   22     Male          Canada  103352.0       NaT
130  120       Wei diaz   48   Female         Germany    1000.0       NaT
134  124       Jane kim   47     Male             Usa   94758.0       NaT
136  126     Ravi kumar   53     Male           India    1000.0       NaT
137  127       Jane lee   34     Male           India   11443.0       NaT
140  130       Sara lee    5   Female           India   10319.0       NaT
143  133    Maria brown   47   Female    Not Provided   75000.0       NaT
144  134    Emma garcia   53     Male             Usa   30845.0       NaT
150  140      Mike diaz    5   Female  United Kingdom    1000.0       NaT
153  143  Nina martinez   49  Unknown             Usa   29000.0       NaT
155  145   Sam williams   45  Unknown           India   13968.0       NaT
156  146     Sara brown   49     Male           India  116000.0       NaT
157  146     Sara brown   31     Male           India  116000.0       NaT
158  147     Mike kumar   36   Female          Canada   88968.0       NaT
160  149      Lisa chen   37   Female             Usa  110798.0       NaT
161  150    Mike garcia   31     Male  United Kingdom   93084.0       NaT
166  155       Ravi lee   57   Female             Usa   35357.0       NaT
168  157     Emma brown   64   Female          Canada   33000.0       NaT
174  162  Fatima nguyen   52     Male           India   15700.0       NaT

                 department                         email  performance_rating  \
5                     Sales  ravi.williams395@example.com                   3
6              Not Provided                  Not Provided                   3
15                    Sales                  Not Provided                   3
20               Operations       ali.khan159@example.com                   4
23   Information Technology       sam.chen680@example.com                   3
30                Marketing      nina.wang241@example.com                   2
31               Operations                  Not Provided                   3
32                    Sales      zoe.rossi861@example.com                   3
35                Marketing                  Not Provided                   3
39           Human Resource     anna.ahmed339@example.com                   3
40           Human Resource     anna.ahmed339@example.com                   3
43             Not Provided      mike.diaz634@example.com                   2
52               Operations     john.rossi280@example.com                   4
53                Marketing                  Not Provided                   3
58                  Finance     anna.smith812@example.com                   2
60   Information Technology      wei.kumar282@example.com                   5
61                    Sales                  Not Provided                   2
63               Operations      ali.ahmed689@example.com                   3
68                    Sales                  Not Provided                   5
69                    Sales       john.khan68@example.com                   3
71               Operations   lisa.johnson382@example.com                   3
72                Marketing                  Not Provided                   3
74   Information Technology                  Not Provided                   4
75   Information Technology                  Not Provided                   4
90                    Sales                  Not Provided                   2
91             Not Provided      ali.rossi638@example.com                   2
93               Operations      nina.khan775@example.com                   3
94   Information Technology                  Not Provided                   5
96           Human Resource   anna.johnson360@example.com                   3
100  Information Technology                  Not Provided                   1
102          Human Resource      tom.brown282@example.com                   3
103            Not Provided      sam.brown591@example.com                   2
107               Marketing                  Not Provided                   2
108                   Sales    maria.garcia47@example.com                   2
109          Human Resource                  Not Provided                   3
110                   Sales  sara.martinez598@example.com                   3
120               Marketing   fatima.ahmed781@example.com                   3
121          Human Resource                  Not Provided                   1
124                 Finance                  Not Provided                   1
126                   Sales     john.ahmed412@example.com                   1
130            Not Provided       wei.diaz491@example.com                   2
134              Operations                  Not Provided                   5
136                   Sales                  Not Provided                   5
137  Information Technology       jane.lee952@example.com                   3
140          Human Resource       sara.lee525@example.com                   3
143              Operations    maria.brown649@example.com                   3
144                   Sales    emma.garcia839@example.com                   3
150                 Finance                  Not Provided                   2
153               Marketing  nina.martinez173@example.com                   2
155               Marketing                  Not Provided                   3
156  Information Technology     sara.brown502@example.com                   2
157  Information Technology     sara.brown502@example.com                   2
158          Human Resource                  Not Provided                   3
160                 Finance      lisa.chen170@example.com                   5
161  Information Technology    mike.garcia837@example.com                   2
166  Information Technology                  Not Provided                   5
168                   Sales     emma.brown509@example.com                   3
174                 Finance   fatima.nguyen64@example.com                   3

     years_experience is_active
5                 1.0   Unknown
6                 2.0       Yes
15                2.0       Yes
20                3.0       Yes
23                3.0       Yes
30                3.0        No
31                3.0       Yes
32                1.0        No
35                1.0        No
39                1.0        No
40                2.0        No
43                4.0       Yes
52                3.0       Yes
53                4.0        No
58                3.0        No
60                1.0       Yes
61                3.0       Yes
63                2.0        No
68                3.0        No
69                2.0        No
71                3.0   Unknown
72                3.0        No
74                4.0   Unknown
75                1.0   Unknown
90                3.0        No
91                2.0   Unknown
93                3.0        No
94                3.0        No
96                4.0       Yes
100               2.0        No
102               1.0        No
103               3.0        No
107               3.0        No
108               2.0       Yes
109               3.0   Unknown
110               4.0   Unknown
120               4.0       Yes
121               3.0       Yes
124               2.0       Yes
126               3.0        No
130               3.0       Yes
134               1.0        No
136               4.0       Yes
137               3.0       Yes
140               3.0       Yes
143               3.0       Yes
144               3.0   Unknown
150               3.0        No
153               2.0        No
155               3.0       Yes
156               2.0        No
157               3.0        No
158               2.0       Yes
160               2.0   Unknown
161               4.0        No
166               3.0       Yes
168               3.0       Yes
174               3.0       Yes

In [89]:
new_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 178 entries, 0 to 177
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   id                  178 non-null    int64
 1   full_name           178 non-null    object
 2   age                 178 non-null    int64
 3   gender              178 non-null    object
 4   country             178 non-null    object
 5   salary              178 non-null    float64
 6   join_date           120 non-null    datetime64[ns]
 7   department          178 non-null    object
 8   email               178 non-null    object
 9   performance_rating  178 non-null    int64
 10  years_experience    178 non-null    float64
 11  is_active           178 non-null    object
dtypes: datetime64[ns](1), float64(2), int64(3), object(6)
memory usage: 16.8+ KB

In [ ]:
new_df['email'] = new_df['email'].str.strip().str.lower()
new_df['email'] = new_df['email'].replace('invalid_email', np.nan)
new_df['email'] = new_df['email'].str.replace(r'@example$', '@example.com', regex=True)

new_df['email'] = new_df['email'].fillna('Not Provided')
new_df['email'].unique()

In [91]:
new_df = new_df.drop_duplicates()
new_df = new_df.drop_duplicates(subset=['id'], keep='first')

In [ ]:
new_df.drop_duplicates(keep='first').reset_index(drop=True)

In [92]:
new_df.to_csv('clean_Date_1.csv', index=False)